name: Prod Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'src/**'

env:
  SFDX_CLI_URL: https://developer.salesforce.com/media/salesforce-cli/sfdx/channels/stable/sfdx-linux-x64.tar.xz
  PROD_ORG_ALIAS: prod

# Required secrets:
# 1. PROD_SFDX_URL - SFDX auth URL of the production org where the package has to be deployed
# 2. CODECOV_TOKEN - Codecov token needed for test coverage overview, required only for private repositories

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 'Install jq'
        run: sudo apt update && sudo apt -y install jq

      - name: 'Install Salesforce CLI'
        run: |
          wget ${{ env.SFDX_CLI_URL }}
          mkdir ~/sfdx
          tar xJf sfdx-linux-x64.tar.xz -C ~/sfdx --strip-components 1
          echo "$HOME/sfdx/bin" >> $GITHUB_PATH
          ~/sfdx/bin/sfdx version

      - name: 'Checkout source code'
        uses: actions/checkout@v3

      - name: 'Authenticate Production'
        shell: bash
        run: |
          echo ${{ secrets.PROD_SFDX_URL }} > ./PROD_SFDX_URL.txt
          secretFileSize=$(wc -c "./PROD_SFDX_URL.txt" | awk '{print $1}')
          if [ $secretFileSize == 1 ]; then
            echo "Missing PROD_SFDX_URL secret. Is this workflow running on a fork?";
            exit 1;
          fi
          sfdx auth:sfdxurl:store -f ./PROD_SFDX_URL.txt -a ${{ env.PROD_ORG_ALIAS }} -d

      - name: 'Fetch latest package version'
        run: echo "LATEST_PACKAGE_VERSION_ID=$(cat sfdx-project.json | jq '.packageAliases | to_entries | last.value' -r)" >> $GITHUB_ENV

      - name: 'Deploy Package'
        run: sfdx package:install -p ${{ env.LATEST_PACKAGE_VERSION_ID }} -w 10 -b 10 -o ${{ env.PROD_ORG_ALIAS }} -r
