global class CommonConstants {
    global static final String EMPTY = '';
    global static final String DOT = '.';
    global static final String COMMA = ',';
    global static final String COLON = ':';
    global static final String SEMICOLON = ';';
    global static final String DOUBLE_QUOTES = '"';
    global static final String SPACE = ' ';
    global static final String LINE_BREAK = '\n';

    global static final String BRACE_LEFT = '{';
    global static final String BRACE_RIGHT = '}';
    global static final String PARENTHESE_LEFT = '(';
    global static final String PARENTHESE_RIGHT = ')';

    global static final Integer FIRST_ELEMENT = 0;

    global static final String FIRST_FORMAT_PARAM = '{0}';
}
