public class CommonConstants {
    public static final String EMPTY = '';
    public static final String DOT = '.';
    public static final String COMMA = ',';
    public static final String COLON = ':';
    public static final String SEMICOLON = ';';
    public static final String DOUBLE_QUOTES = '\"';
    public static final String SPACE = ' ';
    public static final String LINE_BREAK = '\n';
    public static final String UNDERSCORE = '_';

    public static final String BRACE_LEFT = '{';
    public static final String BRACE_RIGHT = '}';
    public static final String PARENTHESE_LEFT = '(';
    public static final String PARENTHESE_RIGHT = ')';

    public static final Integer FIRST_ELEMENT = 0;

    public static final String FIRST_FORMAT_PARAM = '{0}';
}
